package sortaplicacion;



import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KrRD
 */
public class Ordenar extends javax.swing.JFrame {

    /**
     * Creates new form Ordenar
     */
    public Ordenar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbordenadores = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtnumero1 = new javax.swing.JTextField();
        txtnumero2 = new javax.swing.JTextField();
        txtnumero3 = new javax.swing.JTextField();
        txtnumero4 = new javax.swing.JTextField();
        txtnumero5 = new javax.swing.JTextField();
        txtnumero7 = new javax.swing.JTextField();
        txtnumero6 = new javax.swing.JTextField();
        txtnumero8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnumber7 = new javax.swing.JTextField();
        txtnumber6 = new javax.swing.JTextField();
        txtnumber5 = new javax.swing.JTextField();
        txtnumber4 = new javax.swing.JTextField();
        txtnumber3 = new javax.swing.JTextField();
        txtnumber2 = new javax.swing.JTextField();
        txtnumber1 = new javax.swing.JTextField();
        txtnumber8 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcbordenadores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "InsertionSort", "SelectionSort", "BubleSort" }));
        jcbordenadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbordenadoresActionPerformed(evt);
            }
        });

        jLabel1.setText("Desordenados:");

        jLabel2.setText("Ordenados:");

        jMenu1.setText("Opciones");

        jMenuItem2.setText("Limpiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbordenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtnumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumber8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jcbordenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbordenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbordenadoresActionPerformed
       
        int ordenadores = jcbordenadores.getSelectedIndex();

        if (ordenadores == 0) {
            try {

                int numeros[] = new int[8];

                int numero1 = Integer.parseInt(this.txtnumero1.getText());
                int numero2 = Integer.parseInt(this.txtnumero2.getText());
                int numero3 = Integer.parseInt(this.txtnumero3.getText());
                int numero4 = Integer.parseInt(this.txtnumero4.getText());
                int numero5 = Integer.parseInt(this.txtnumero5.getText());
                int numero6 = Integer.parseInt(this.txtnumero6.getText());
                int numero7 = Integer.parseInt(this.txtnumero7.getText());
                int numero8 = Integer.parseInt(this.txtnumero8.getText());

                numeros[0] = numero1;
                numeros[1] = numero2;
                numeros[2] = numero3;
                numeros[3] = numero4;
                numeros[4] = numero5;
                numeros[5] = numero6;
                numeros[6] = numero7;
                numeros[7] = numero8;

                Ordenador ord = new Ordenador();
                ord.insertionSort(numeros);

                txtnumber1.setText(String.valueOf(numeros[0]));
                txtnumber2.setText(String.valueOf(numeros[1]));
                txtnumber3.setText(String.valueOf(numeros[2]));
                txtnumber4.setText(String.valueOf(numeros[3]));
                txtnumber5.setText(String.valueOf(numeros[4]));
                txtnumber6.setText(String.valueOf(numeros[5]));
                txtnumber7.setText(String.valueOf(numeros[6]));
                txtnumber8.setText(String.valueOf(numeros[7]));

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(this, " no se puede realizar la operación, "
                        + " puede que no halla ingresado valores "
                        + "\n o los valores ingresados no son validos", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (ordenadores == 1) {

            try {

                int numeros[] = new int[8];

                int numero1 = Integer.parseInt(this.txtnumero1.getText());
                int numero2 = Integer.parseInt(this.txtnumero2.getText());
                int numero3 = Integer.parseInt(this.txtnumero3.getText());
                int numero4 = Integer.parseInt(this.txtnumero4.getText());
                int numero5 = Integer.parseInt(this.txtnumero5.getText());
                int numero6 = Integer.parseInt(this.txtnumero6.getText());
                int numero7 = Integer.parseInt(this.txtnumero7.getText());
                int numero8 = Integer.parseInt(this.txtnumero8.getText());

                numeros[0] = numero1;
                numeros[1] = numero2;
                numeros[2] = numero3;
                numeros[3] = numero4;
                numeros[4] = numero5;
                numeros[5] = numero6;
                numeros[6] = numero7;
                numeros[7] = numero8;

                Ordenador ord = new Ordenador();
                ord.selectionSort(numeros);

                txtnumber1.setText(String.valueOf(numeros[0]));
                txtnumber2.setText(String.valueOf(numeros[1]));
                txtnumber3.setText(String.valueOf(numeros[2]));
                txtnumber4.setText(String.valueOf(numeros[3]));
                txtnumber5.setText(String.valueOf(numeros[4]));
                txtnumber6.setText(String.valueOf(numeros[5]));
                txtnumber7.setText(String.valueOf(numeros[6]));
                txtnumber8.setText(String.valueOf(numeros[7]));

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(this, " no se puede realizar la operación, "
                        + " puede que no halla ingresado valores "
                        + "\n o los valores ingresados no son validos", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if (ordenadores == 2) {
            try {

                int numeros[] = new int[8];

                int numero1 = Integer.parseInt(this.txtnumero1.getText());
                int numero2 = Integer.parseInt(this.txtnumero2.getText());
                int numero3 = Integer.parseInt(this.txtnumero3.getText());
                int numero4 = Integer.parseInt(this.txtnumero4.getText());
                int numero5 = Integer.parseInt(this.txtnumero5.getText());
                int numero6 = Integer.parseInt(this.txtnumero6.getText());
                int numero7 = Integer.parseInt(this.txtnumero7.getText());
                int numero8 = Integer.parseInt(this.txtnumero8.getText());

                numeros[0] = numero1;
                numeros[1] = numero2;
                numeros[2] = numero3;
                numeros[3] = numero4;
                numeros[4] = numero5;
                numeros[5] = numero6;
                numeros[6] = numero7;
                numeros[7] = numero8;

                Ordenador ord = new Ordenador();
                ord.bubbleSort(numeros);

                txtnumber1.setText(String.valueOf(numeros[0]));
                txtnumber2.setText(String.valueOf(numeros[1]));
                txtnumber3.setText(String.valueOf(numeros[2]));
                txtnumber4.setText(String.valueOf(numeros[3]));
                txtnumber5.setText(String.valueOf(numeros[4]));
                txtnumber6.setText(String.valueOf(numeros[5]));
                txtnumber7.setText(String.valueOf(numeros[6]));
                txtnumber8.setText(String.valueOf(numeros[7]));

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(this, " no se puede realizar la operación, "
                        + " puede que no halla ingresado valores "
                        + "\n o los valores ingresados no son validos", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jcbordenadoresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.txtnumero1.setText(" ");
        this.txtnumero2.setText(" ");
        this.txtnumero3.setText(" ");
        this.txtnumero4.setText(" ");
        this.txtnumero5.setText(" ");
        this.txtnumero6.setText(" ");
        this.txtnumero7.setText(" ");
        this.txtnumero8.setText(" ");

        this.txtnumero1.grabFocus();

        this.txtnumber1.setText(" ");
        this.txtnumber2.setText(" ");
        this.txtnumber3.setText(" ");
        this.txtnumber4.setText(" ");
        this.txtnumber5.setText(" ");
        this.txtnumber6.setText(" ");
        this.txtnumber7.setText(" ");
        this.txtnumber8.setText(" ");

        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ordenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ordenar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JComboBox jcbordenadores;
    private javax.swing.JTextField txtnumber1;
    private javax.swing.JTextField txtnumber2;
    private javax.swing.JTextField txtnumber3;
    private javax.swing.JTextField txtnumber4;
    private javax.swing.JTextField txtnumber5;
    private javax.swing.JTextField txtnumber6;
    private javax.swing.JTextField txtnumber7;
    private javax.swing.JTextField txtnumber8;
    private javax.swing.JTextField txtnumero1;
    private javax.swing.JTextField txtnumero2;
    private javax.swing.JTextField txtnumero3;
    private javax.swing.JTextField txtnumero4;
    private javax.swing.JTextField txtnumero5;
    private javax.swing.JTextField txtnumero6;
    private javax.swing.JTextField txtnumero7;
    private javax.swing.JTextField txtnumero8;
    // End of variables declaration//GEN-END:variables
}
